abstract: Automatically clean up your filesystem after tests
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Test-File-Cleaner
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  File::Basename: 0
  File::Find::Rule: 0.02
  File::Spec: 0.82
  File::stat: 0
  perl: 5.005
version: 0.03
